# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHRG8BG1KlGsyXLabdq5nN2ohWXTwp7W
"""

import pandas as pd
import unicodedata
import re
from google.colab import files


df = pd.read_csv('/content/players_data-2024_2025.csv')


def ultra_clean_names(text):
    if isinstance(text, str):

        nfkd_form = unicodedata.normalize('NFKD', text)
        text = "".join([c for c in nfkd_form if not unicodedata.combining(c)])

        text = re.sub(r'[^a-zA-Z0-9\s-]', '', text)
        return text.strip()
    return text


df_final = df.iloc[:, :46].copy()


cols_to_drop = df_final.columns[29:37]
df_final = df_final.drop(columns=cols_to_drop)


columns_to_fix = ['Player', 'Squad', 'Comp']
for col in columns_to_fix:
    if col in df_final.columns:
        df_final[col] = df_final[col].apply(ultra_clean_names)


if 'Min' in df_final.columns:
    df_final = df_final[df_final['Min'] >= 10]


df_final = df_final.dropna()


for col in ['Age', 'Born']:
    if col in df_final.columns:
        df_final[col] = df_final[col].fillna(0).astype(int)


output_name = 'Football_Data_Final_Professional.csv'
df_final.to_csv(output_name, index=False, encoding='utf-8-sig')

print(f" {output_name}")
files.download(output_name)